Myblog/urls.py
from django.urls import path,include
from . import views

app_name= 'Myblog'
urlpatterns = [
    path('', views.myblog,name='myblog'),
    path('<int:blog_id>', views.detail,name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name='home'),
    path('Myblog/', include('Myblog.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Myblog/models.py
from django.db import models

class Myblog(models.Model):
    title=models.CharField(max_length=200)
    description= models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.
class Portfolio(models.Model):
    title=models.CharField(max_length=100)
    description= models.CharField(max_length=250)
    url= models.URLField(blank=True)
    image=models.ImageField(upload_to='portfolio/images/')

    def __str__(self):
        return self.title

Myblog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Myblog

def myblog(request):
    blog=Myblog.objects.all()
    return render(request, 'Myblog/myblog.html',{'blog':blog})

def detail(request,blog_id):
    blog=get_object_or_404(Myblog,pk=blog_id)
    return render(request,'Myblog\detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Portfolio
# Create your views here.
def home(request):
    prt=Portfolio.objects.all()
    return render(request, 'portfolio/home.html',{'prt':prt})

Myblog/templates/Myblog/detail.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}
<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>
<h5 class="text-center text-muted mb-5">{{ blog.date|date:'M d Y' }}</h5>
{{blog.description|safe}}

{% endblock %}

Myblog/templates/Myblog/myblog.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}
<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Sanjay has written {{ blog.count }} blog  {{ blog.count|pluralize }}</h3>
{% for blg in  blog %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
  <a href="{% url 'Myblog:detail' blg.id %}">
    <h2>{{ blg.title}}</h2>
  </a>
    <h5 class="text_muted">{{ blg.date|date:'M d Y'|upper }}</h5>
    <h4>{{ blg.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>

{% endfor %}
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

      <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

      <link rel="icon" type="image/png" href="{% static "portfolio/Logo.png" %}" >

      <title>Sanjay Shah</title>
    </head>
<body>
  <nav id="topNav" class="navbar navbar-expand-lg navbar-light bg-light">

    <img src="{% static "portfolio/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Sanjay's Logo">
            <span></span>
  <a class="navbar-brand" href="{% url 'home' %}" >home</a>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
 </button>
       <div class="collapse navbar-collapse text-center" id="navbarNav">
         <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/sanjay-shah-8a1b3521/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
             <a class="nav-link" href="https://twitter.com/ZappyCode" target="_blank">Twitter</a>
          </li>
          <li>
           <a role="button" href="{% url 'Myblog:myblog' %}" class="btn btn-primary">Blog</a>
          </li>
      </ul>
     </div>
   </div>
 </nav>
<div class="container">
{% block content %}

{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
     <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
   </body>
 </html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load static %}


{% block content %}
<body>
  <div class="row justify-content-center my-3">
  <div class="c">
    <img src="{% static 'portfolio/bg.jpg'%}" class="img-fluid">
  </div>
</div>
<div style= "background-image; url ({% static 'portfolio/bg.jpg'%}) ">
<h2 class ="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for p in  prt %}
  <div class="col-lg-4 col-md-6">
  {% if p.url %}
   <a href="{{ p.url }}">
     <img src="{{ p.image.url }}" class="img-fluid mb-2">
   </a>
   {% else %}
    <img src="{{ p.image.url }}" class="img-fluid mb-2">
   {% endif %}
   <h3>{{ p.title}}</h3>
   <p>{{ p.description }}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}
</body>